version: '3'
services:
  cpp:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "8080:8080"
    volumes:
      - ../CppND-Capstone:/CppND-Capstone
      - ../options/src:/CppND-Capstone/src
      - ../options/test/simple_tests.cpp:/CppND-Capstone/src/main.cpp
      - ../scripts/build-project.simpletests.sh:/build-project.simpletests.sh
    environment:
        - DISPLAY=docker.for.mac.host.internal:0
    command: >
      bash -c "
      chmod +x /build-project.simpletests.sh &&
      export DISPLAY=host.docker.internal:0 &&
      /build-project.simpletests.sh
      "
