version: '3'
services:
  cpp:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "8080:8080"
    volumes:
      - ../CppND-Capstone:/CppND-Capstone
      - ../scripts/build-project.basic.sh:/build-project.basic.sh
    environment:
        - DISPLAY=docker.for.mac.host.internal:0
    command: >
      bash -c "
      chmod +x /build-project.basic.sh &&
      export DISPLAY=host.docker.internal:0 &&
      /build-project.basic.sh
      "
